### ISSUE TITLE
youtu.be links

### ISSUE THREAD

**Issue by ghost** [rasjani/plugin.video.reddit_tv#6]
hi the addon doesn't show links formatted as youtu.be

**Comment by ghost** [comment]
hi will this be resolved? thanks

**Comment by rasjani** [comment]
working on it right now. Initial impression is that it _should_ work because the "site" search string does include site:youtu.be, so its bit open why they don't show up in the listing ..

EDIT: It was quite evident after checking the code a bit further. reddit search does include the youtu.be in search results but matching url uses only youtube.com..

**Comment by ghost** [comment]
hi I dont get it :) is it a easy fix, to show also youtu.be links in kodi? thanks!

**Comment by rasjani** [comment]
Fix was done yesterday and im 100% sure that i also pushed but apparently its not here..  Later today..

**Comment by ghost** [comment]
ok thanks!
